// Export design system tokens in various formats.

import type { DesignSystem, ScaleStep } from "./types";
import { generateScale } from "./color";

function indent(str: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return str.split("\n").map((l) => pad + l).join("\n");
}

export function exportCssVariables(system: DesignSystem, mode: "light" | "dark" | "both"): string {
  const lines: string[] = [];

  function colorVars(prefix: string, hex: string, label: string) {
    const scale = generateScale(hex);
    lines.push(`  /* ${label} */`);
    lines.push(`  --${prefix}: ${hex};`);
    for (const [step, value] of Object.entries(scale)) {
      lines.push(`  --${prefix}-${step}: ${value};`);
    }
  }

  function addVarsForMode(m: "light" | "dark") {
    const c = system.colors;
    const keys = ["primary", "secondary", "accent", "neutral", "success", "warning", "error", "info"] as const;
    for (const key of keys) {
      colorVars(key, c[key][m], key);
    }
    lines.push("");
    lines.push("  /* Typography */");
    lines.push(`  --font-heading: "${system.typography.heading.family}", ${system.typography.heading.category};`);
    lines.push(`  --font-body: "${system.typography.body.family}", ${system.typography.body.category};`);
    lines.push(`  --font-base-size: ${system.typography.baseSize}px;`);
    lines.push(`  --type-scale-ratio: ${system.typography.scaleRatio};`);
    lines.push("");
    lines.push("  /* Spacing */");
    lines.push(`  --spacing-base: ${system.spacing.base}px;`);
    for (const step of system.spacing.steps) {
      lines.push(`  --spacing-${step}: ${system.spacing.base * step}px;`);
    }
    lines.push("");
    lines.push("  /* Radius */");
    lines.push(`  --radius-sm: ${system.effects.radius.sm}px;`);
    lines.push(`  --radius-md: ${system.effects.radius.md}px;`);
    lines.push(`  --radius-lg: ${system.effects.radius.lg}px;`);
    lines.push(`  --radius-xl: ${system.effects.radius.xl}px;`);
    lines.push("");
    lines.push("  /* Shadows */");
    for (const [key, val] of Object.entries(system.effects.shadows)) {
      lines.push(`  --shadow-${key}: ${val};`);
    }
    lines.push("");
    lines.push("  /* Grid */");
    lines.push(`  --grid-columns: ${system.grid.columns};`);
    lines.push(`  --grid-gutter: ${system.grid.gutter}px;`);
    lines.push(`  --grid-max-width: ${system.grid.maxWidth}px;`);
    lines.push("");
    lines.push("  /* Breakpoints */");
    lines.push(`  --bp-mobile: ${system.breakpoints.mobile}px;`);
    lines.push(`  --bp-tablet: ${system.breakpoints.tablet}px;`);
    lines.push(`  --bp-desktop: ${system.breakpoints.desktop}px;`);
    lines.push(`  --bp-wide: ${system.breakpoints.wide}px;`);
  }

  if (mode === "both") {
    lines.push(":root {");
    addVarsForMode("light");
    lines.push("}");
    lines.push("");
    lines.push("@media (prefers-color-scheme: dark) {");
    lines.push("  :root {");
    const darkLines: string[] = [];
    const origLines = lines;
    const tempLines: string[] = [];
    lines.length = 0;
    lines.push(...origLines);
    // Restart for dark
    const darkSection: string[] = [];
    const c = system.colors;
    const keys = ["primary", "secondary", "accent", "neutral", "success", "warning", "error", "info"] as const;
    for (const key of keys) {
      const scale = generateScale(c[key].dark);
      darkSection.push(`    --${key}: ${c[key].dark};`);
      for (const [step, value] of Object.entries(scale)) {
        darkSection.push(`    --${key}-${step}: ${value};`);
      }
    }
    lines.push(...darkSection);
    lines.push("  }");
    lines.push("}");
  } else {
    lines.push(":root {");
    addVarsForMode(mode);
    lines.push("}");
  }

  return lines.join("\n");
}

export function exportTailwindConfig(system: DesignSystem): string {
  const c = system.colors;
  const keys = ["primary", "secondary", "accent", "neutral", "success", "warning", "error", "info"] as const;

  const colorEntries: string[] = [];
  for (const key of keys) {
    const scale = generateScale(c[key].light);
    const scaleEntries = Object.entries(scale)
      .map(([step, val]) => `        ${step}: "${val}"`)
      .join(",\n");
    colorEntries.push(`      ${key}: {\n        DEFAULT: "${c[key].light}",\n${scaleEntries}\n      }`);
  }

  return `// tailwind.config.ts — generated by Design System Creator
import type { Config } from "tailwindcss";

export default {
  theme: {
    extend: {
      colors: {
${colorEntries.join(",\n")}
      },
      fontFamily: {
        heading: ["${system.typography.heading.family}", "${system.typography.heading.category}"],
        body: ["${system.typography.body.family}", "${system.typography.body.category}"],
      },
      fontSize: {
        base: "${system.typography.baseSize}px",
      },
      spacing: {
${system.spacing.steps.map((s) => `        "${s}": "${system.spacing.base * s}px"`).join(",\n")}
      },
      borderRadius: {
        sm: "${system.effects.radius.sm}px",
        md: "${system.effects.radius.md}px",
        lg: "${system.effects.radius.lg}px",
        xl: "${system.effects.radius.xl}px",
      },
      boxShadow: {
${Object.entries(system.effects.shadows).map(([k, v]) => `        "${k}": "${v}"`).join(",\n")}
      },
      screens: {
        mobile: "${system.breakpoints.mobile}px",
        tablet: "${system.breakpoints.tablet}px",
        desktop: "${system.breakpoints.desktop}px",
        wide: "${system.breakpoints.wide}px",
      },
      maxWidth: {
        container: "${system.grid.maxWidth}px",
      },
    },
  },
} satisfies Config;
`;
}

export function exportJsonTokens(system: DesignSystem): string {
  const c = system.colors;
  const keys = ["primary", "secondary", "accent", "neutral", "success", "warning", "error", "info"] as const;

  const tokens: Record<string, unknown> = {
    colors: {} as Record<string, unknown>,
    typography: {
      fontFamilies: {
        heading: system.typography.heading.family,
        body: system.typography.body.family,
      },
      baseSize: system.typography.baseSize,
      scaleRatio: system.typography.scaleRatio,
      levels: system.typography.levels,
    },
    spacing: {
      base: system.spacing.base,
      scale: Object.fromEntries(
        system.spacing.steps.map((s) => [s, system.spacing.base * s])
      ),
    },
    effects: {
      radius: system.effects.radius,
      shadows: system.effects.shadows,
      borderWidth: system.effects.borderWidth,
    },
    grid: system.grid,
    breakpoints: system.breakpoints,
  };

  for (const key of keys) {
    const scale = generateScale(c[key].light);
    (tokens.colors as Record<string, unknown>)[key] = {
      light: c[key].light,
      dark: c[key].dark,
      scale,
    };
  }

  return JSON.stringify(tokens, null, 2);
}

export type ExportFormat = "css" | "tailwind" | "json";

export function exportDesignSystem(system: DesignSystem, format: ExportFormat): string {
  switch (format) {
    case "css":
      return exportCssVariables(system, "both");
    case "tailwind":
      return exportTailwindConfig(system);
    case "json":
      return exportJsonTokens(system);
  }
}
