// Auto-extracted UX guideline database (source: ui-ux-pro-max skill,
// data/ux-guidelines.csv + the priority table from SKILL.md).
// 98 concrete Do/Don't rules plus the 10 top-level rule categories ranked by
// impact, used to power a live review checklist against the active project.

export interface UxGuideline {
  id: string;
  category: string;
  issue: string;
  platform: string;
  description: string;
  doText: string;
  dontText: string;
  severity: string;
}

export const UX_GUIDELINES: UxGuideline[] = [
  {
    id: "1-smooth-scroll",
    category: "Navigation",
    issue: "Smooth Scroll",
    platform: "Web",
    description: "Anchor links should scroll smoothly to target section",
    doText: "Use scroll-behavior: smooth on html element",
    dontText: "Jump directly without transition",
    severity: "High",
  },
  {
    id: "2-sticky-navigation",
    category: "Navigation",
    issue: "Sticky Navigation",
    platform: "Web",
    description: "Fixed nav should not obscure content",
    doText: "Add padding-top to body equal to nav height",
    dontText: "Let nav overlap first section content",
    severity: "Medium",
  },
  {
    id: "3-active-state",
    category: "Navigation",
    issue: "Active State",
    platform: "All",
    description: "Current page/section should be visually indicated",
    doText: "Highlight active nav item with color/underline",
    dontText: "No visual feedback on current location",
    severity: "Medium",
  },
  {
    id: "4-back-button",
    category: "Navigation",
    issue: "Back Button",
    platform: "Mobile",
    description: "Users expect back to work predictably",
    doText: "Preserve navigation history properly",
    dontText: "Break browser/app back button behavior",
    severity: "High",
  },
  {
    id: "5-deep-linking",
    category: "Navigation",
    issue: "Deep Linking",
    platform: "All",
    description: "URLs should reflect current state for sharing",
    doText: "Update URL on state/view changes",
    dontText: "Static URLs for dynamic content",
    severity: "Medium",
  },
  {
    id: "6-breadcrumbs",
    category: "Navigation",
    issue: "Breadcrumbs",
    platform: "Web",
    description: "Show user location in site hierarchy",
    doText: "Use for sites with 3+ levels of depth",
    dontText: "Use for flat single-level sites",
    severity: "Low",
  },
  {
    id: "7-excessive-motion",
    category: "Animation",
    issue: "Excessive Motion",
    platform: "All",
    description: "Too many animations cause distraction and motion sickness",
    doText: "Animate 1-2 key elements per view maximum",
    dontText: "Animate everything that moves",
    severity: "High",
  },
  {
    id: "8-duration-timing",
    category: "Animation",
    issue: "Duration Timing",
    platform: "All",
    description: "Animations should feel responsive not sluggish",
    doText: "Use 150-300ms for micro-interactions",
    dontText: "Use animations longer than 500ms for UI",
    severity: "Medium",
  },
  {
    id: "9-reduced-motion",
    category: "Animation",
    issue: "Reduced Motion",
    platform: "All",
    description: "Respect user's motion preferences",
    doText: "Check prefers-reduced-motion media query",
    dontText: "Ignore accessibility motion settings",
    severity: "High",
  },
  {
    id: "10-loading-states",
    category: "Animation",
    issue: "Loading States",
    platform: "All",
    description: "Show feedback during async operations",
    doText: "Use skeleton screens or spinners",
    dontText: "Leave UI frozen with no feedback",
    severity: "High",
  },
  {
    id: "11-hover-vs-tap",
    category: "Animation",
    issue: "Hover vs Tap",
    platform: "All",
    description: "Hover effects don't work on touch devices",
    doText: "Use click/tap for primary interactions",
    dontText: "Rely only on hover for important actions",
    severity: "High",
  },
  {
    id: "12-continuous-animation",
    category: "Animation",
    issue: "Continuous Animation",
    platform: "All",
    description: "Infinite animations are distracting",
    doText: "Use for loading indicators only",
    dontText: "Use for decorative elements",
    severity: "Medium",
  },
  {
    id: "13-transform-performance",
    category: "Animation",
    issue: "Transform Performance",
    platform: "Web",
    description: "Some CSS properties trigger expensive repaints",
    doText: "Use transform and opacity for animations",
    dontText: "Animate width/height/top/left properties",
    severity: "Medium",
  },
  {
    id: "14-easing-functions",
    category: "Animation",
    issue: "Easing Functions",
    platform: "All",
    description: "Linear motion feels robotic",
    doText: "Use ease-out for entering ease-in for exiting",
    dontText: "Use linear for UI transitions",
    severity: "Low",
  },
  {
    id: "15-z-index-management",
    category: "Layout",
    issue: "Z-Index Management",
    platform: "Web",
    description: "Stacking context conflicts cause hidden elements",
    doText: "Define z-index scale system (10 20 30 50)",
    dontText: "Use arbitrary large z-index values",
    severity: "High",
  },
  {
    id: "16-overflow-hidden",
    category: "Layout",
    issue: "Overflow Hidden",
    platform: "Web",
    description: "Hidden overflow can clip important content",
    doText: "Test all content fits within containers",
    dontText: "Blindly apply overflow-hidden",
    severity: "Medium",
  },
  {
    id: "17-fixed-positioning",
    category: "Layout",
    issue: "Fixed Positioning",
    platform: "Web",
    description: "Fixed elements can overlap or be inaccessible",
    doText: "Account for safe areas and other fixed elements",
    dontText: "Stack multiple fixed elements carelessly",
    severity: "Medium",
  },
  {
    id: "18-stacking-context",
    category: "Layout",
    issue: "Stacking Context",
    platform: "Web",
    description: "New stacking contexts reset z-index",
    doText: "Understand what creates new stacking context",
    dontText: "Expect z-index to work across contexts",
    severity: "Medium",
  },
  {
    id: "19-content-jumping",
    category: "Layout",
    issue: "Content Jumping",
    platform: "Web",
    description: "Layout shift when content loads is jarring",
    doText: "Reserve space for async content",
    dontText: "Let images/content push layout around",
    severity: "High",
  },
  {
    id: "20-viewport-units",
    category: "Layout",
    issue: "Viewport Units",
    platform: "Web",
    description: "100vh can be problematic on mobile browsers",
    doText: "Use dvh or account for mobile browser chrome",
    dontText: "Use 100vh for full-screen mobile layouts",
    severity: "Medium",
  },
  {
    id: "21-container-width",
    category: "Layout",
    issue: "Container Width",
    platform: "Web",
    description: "Content too wide is hard to read",
    doText: "Limit max-width for text content (65-75ch)",
    dontText: "Let text span full viewport width",
    severity: "Medium",
  },
  {
    id: "22-touch-target-size",
    category: "Touch",
    issue: "Touch Target Size",
    platform: "Mobile",
    description: "Small buttons are hard to tap accurately",
    doText: "Minimum 44x44px touch targets",
    dontText: "Tiny clickable areas",
    severity: "High",
  },
  {
    id: "23-touch-spacing",
    category: "Touch",
    issue: "Touch Spacing",
    platform: "Mobile",
    description: "Adjacent touch targets need adequate spacing",
    doText: "Minimum 8px gap between touch targets",
    dontText: "Tightly packed clickable elements",
    severity: "Medium",
  },
  {
    id: "24-gesture-conflicts",
    category: "Touch",
    issue: "Gesture Conflicts",
    platform: "Mobile",
    description: "Custom gestures can conflict with system",
    doText: "Avoid horizontal swipe on main content",
    dontText: "Override system gestures",
    severity: "Medium",
  },
  {
    id: "25-tap-delay",
    category: "Touch",
    issue: "Tap Delay",
    platform: "Mobile",
    description: "300ms tap delay feels laggy",
    doText: "Use touch-action CSS or fastclick",
    dontText: "Default mobile tap handling",
    severity: "Medium",
  },
  {
    id: "26-pull-to-refresh",
    category: "Touch",
    issue: "Pull to Refresh",
    platform: "Mobile",
    description: "Accidental refresh is frustrating",
    doText: "Disable where not needed",
    dontText: "Enable by default everywhere",
    severity: "Low",
  },
  {
    id: "27-haptic-feedback",
    category: "Touch",
    issue: "Haptic Feedback",
    platform: "Mobile",
    description: "Tactile feedback improves interaction feel",
    doText: "Use for confirmations and important actions",
    dontText: "Overuse vibration feedback",
    severity: "Low",
  },
  {
    id: "28-focus-states",
    category: "Interaction",
    issue: "Focus States",
    platform: "All",
    description: "Keyboard users need visible focus indicators",
    doText: "Use visible focus rings on interactive elements",
    dontText: "Remove focus outline without replacement",
    severity: "High",
  },
  {
    id: "29-hover-states",
    category: "Interaction",
    issue: "Hover States",
    platform: "Web",
    description: "Visual feedback on interactive elements",
    doText: "Change cursor and add subtle visual change",
    dontText: "No hover feedback on clickable elements",
    severity: "Medium",
  },
  {
    id: "30-active-states",
    category: "Interaction",
    issue: "Active States",
    platform: "All",
    description: "Show immediate feedback on press/click",
    doText: "Add pressed/active state visual change",
    dontText: "No feedback during interaction",
    severity: "Medium",
  },
  {
    id: "31-disabled-states",
    category: "Interaction",
    issue: "Disabled States",
    platform: "All",
    description: "Clearly indicate non-interactive elements",
    doText: "Reduce opacity and change cursor",
    dontText: "Confuse disabled with normal state",
    severity: "Medium",
  },
  {
    id: "32-loading-buttons",
    category: "Interaction",
    issue: "Loading Buttons",
    platform: "All",
    description: "Prevent double submission during async actions",
    doText: "Disable button and show loading state",
    dontText: "Allow multiple clicks during processing",
    severity: "High",
  },
  {
    id: "33-error-feedback",
    category: "Interaction",
    issue: "Error Feedback",
    platform: "All",
    description: "Users need to know when something fails",
    doText: "Show clear error messages near problem",
    dontText: "Silent failures with no feedback",
    severity: "High",
  },
  {
    id: "34-success-feedback",
    category: "Interaction",
    issue: "Success Feedback",
    platform: "All",
    description: "Confirm successful actions to users",
    doText: "Show success message or visual change",
    dontText: "No confirmation of completed action",
    severity: "Medium",
  },
  {
    id: "35-confirmation-dialogs",
    category: "Interaction",
    issue: "Confirmation Dialogs",
    platform: "All",
    description: "Prevent accidental destructive actions",
    doText: "Confirm before delete/irreversible actions",
    dontText: "Delete without confirmation",
    severity: "High",
  },
  {
    id: "36-color-contrast",
    category: "Accessibility",
    issue: "Color Contrast",
    platform: "All",
    description: "Text must be readable against background",
    doText: "Minimum 4.5:1 ratio for normal text",
    dontText: "Low contrast text",
    severity: "High",
  },
  {
    id: "37-color-only",
    category: "Accessibility",
    issue: "Color Only",
    platform: "All",
    description: "Don't convey information by color alone",
    doText: "Use icons/text in addition to color",
    dontText: "Red/green only for error/success",
    severity: "High",
  },
  {
    id: "38-alt-text",
    category: "Accessibility",
    issue: "Alt Text",
    platform: "All",
    description: "Images need text alternatives",
    doText: "Descriptive alt text for meaningful images",
    dontText: "Empty or missing alt attributes",
    severity: "High",
  },
  {
    id: "39-heading-hierarchy",
    category: "Accessibility",
    issue: "Heading Hierarchy",
    platform: "Web",
    description: "Screen readers use headings for navigation",
    doText: "Use sequential heading levels h1-h6",
    dontText: "Skip heading levels or misuse for styling",
    severity: "Medium",
  },
  {
    id: "40-aria-labels",
    category: "Accessibility",
    issue: "ARIA Labels",
    platform: "All",
    description: "Interactive elements need accessible names",
    doText: "Add aria-label for icon-only buttons",
    dontText: "Icon buttons without labels",
    severity: "High",
  },
  {
    id: "41-keyboard-navigation",
    category: "Accessibility",
    issue: "Keyboard Navigation",
    platform: "Web",
    description: "All functionality accessible via keyboard",
    doText: "Tab order matches visual order",
    dontText: "Keyboard traps or illogical tab order",
    severity: "High",
  },
  {
    id: "42-screen-reader",
    category: "Accessibility",
    issue: "Screen Reader",
    platform: "All",
    description: "Content should make sense when read aloud",
    doText: "Use semantic HTML and ARIA properly",
    dontText: "Div soup with no semantics",
    severity: "Medium",
  },
  {
    id: "43-form-labels",
    category: "Accessibility",
    issue: "Form Labels",
    platform: "All",
    description: "Inputs must have associated labels",
    doText: "Use label with for attribute or wrap input",
    dontText: "Placeholder-only inputs",
    severity: "High",
  },
  {
    id: "44-error-messages",
    category: "Accessibility",
    issue: "Error Messages",
    platform: "All",
    description: "Error messages must be announced",
    doText: "Use aria-live or role=alert for errors",
    dontText: "Visual-only error indication",
    severity: "High",
  },
  {
    id: "45-skip-links",
    category: "Accessibility",
    issue: "Skip Links",
    platform: "Web",
    description: "Allow keyboard users to skip navigation",
    doText: "Provide skip to main content link",
    dontText: "No skip link on nav-heavy pages",
    severity: "Medium",
  },
  {
    id: "46-image-optimization",
    category: "Performance",
    issue: "Image Optimization",
    platform: "All",
    description: "Large images slow page load",
    doText: "Use appropriate size and format (WebP)",
    dontText: "Unoptimized full-size images",
    severity: "High",
  },
  {
    id: "47-lazy-loading",
    category: "Performance",
    issue: "Lazy Loading",
    platform: "All",
    description: "Load content as needed",
    doText: "Lazy load below-fold images and content",
    dontText: "Load everything upfront",
    severity: "Medium",
  },
  {
    id: "48-code-splitting",
    category: "Performance",
    issue: "Code Splitting",
    platform: "Web",
    description: "Large bundles slow initial load",
    doText: "Split code by route/feature",
    dontText: "Single large bundle",
    severity: "Medium",
  },
  {
    id: "49-caching",
    category: "Performance",
    issue: "Caching",
    platform: "Web",
    description: "Repeat visits should be fast",
    doText: "Set appropriate cache headers",
    dontText: "No caching strategy",
    severity: "Medium",
  },
  {
    id: "50-font-loading",
    category: "Performance",
    issue: "Font Loading",
    platform: "Web",
    description: "Web fonts can block rendering",
    doText: "Use font-display swap or optional",
    dontText: "Invisible text during font load",
    severity: "Medium",
  },
  {
    id: "51-third-party-scripts",
    category: "Performance",
    issue: "Third Party Scripts",
    platform: "Web",
    description: "External scripts can block rendering",
    doText: "Load non-critical scripts async/defer",
    dontText: "Synchronous third-party scripts",
    severity: "Medium",
  },
  {
    id: "52-bundle-size",
    category: "Performance",
    issue: "Bundle Size",
    platform: "Web",
    description: "Large JavaScript slows interaction",
    doText: "Monitor and minimize bundle size",
    dontText: "Ignore bundle size growth",
    severity: "Medium",
  },
  {
    id: "53-render-blocking",
    category: "Performance",
    issue: "Render Blocking",
    platform: "Web",
    description: "CSS/JS can block first paint",
    doText: "Inline critical CSS defer non-critical",
    dontText: "Large blocking CSS files",
    severity: "Medium",
  },
  {
    id: "54-input-labels",
    category: "Forms",
    issue: "Input Labels",
    platform: "All",
    description: "Every input needs a visible label",
    doText: "Always show label above or beside input",
    dontText: "Placeholder as only label",
    severity: "High",
  },
  {
    id: "55-error-placement",
    category: "Forms",
    issue: "Error Placement",
    platform: "All",
    description: "Errors should appear near the problem",
    doText: "Show error below related input",
    dontText: "Single error message at top of form",
    severity: "Medium",
  },
  {
    id: "56-inline-validation",
    category: "Forms",
    issue: "Inline Validation",
    platform: "All",
    description: "Validate as user types or on blur",
    doText: "Validate on blur for most fields",
    dontText: "Validate only on submit",
    severity: "Medium",
  },
  {
    id: "57-input-types",
    category: "Forms",
    issue: "Input Types",
    platform: "All",
    description: "Use appropriate input types",
    doText: "Use email tel number url etc",
    dontText: "Text input for everything",
    severity: "Medium",
  },
  {
    id: "58-autofill-support",
    category: "Forms",
    issue: "Autofill Support",
    platform: "Web",
    description: "Help browsers autofill correctly",
    doText: "Use autocomplete attribute properly",
    dontText: "Block or ignore autofill",
    severity: "Medium",
  },
  {
    id: "59-required-indicators",
    category: "Forms",
    issue: "Required Indicators",
    platform: "All",
    description: "Mark required fields clearly",
    doText: "Use asterisk or (required) text",
    dontText: "No indication of required fields",
    severity: "Medium",
  },
  {
    id: "60-password-visibility",
    category: "Forms",
    issue: "Password Visibility",
    platform: "All",
    description: "Let users see password while typing",
    doText: "Toggle to show/hide password",
    dontText: "No visibility toggle",
    severity: "Medium",
  },
  {
    id: "61-submit-feedback",
    category: "Forms",
    issue: "Submit Feedback",
    platform: "All",
    description: "Confirm form submission status",
    doText: "Show loading then success/error state",
    dontText: "No feedback after submit",
    severity: "High",
  },
  {
    id: "62-input-affordance",
    category: "Forms",
    issue: "Input Affordance",
    platform: "All",
    description: "Inputs should look interactive",
    doText: "Use distinct input styling",
    dontText: "Inputs that look like plain text",
    severity: "Medium",
  },
  {
    id: "63-mobile-keyboards",
    category: "Forms",
    issue: "Mobile Keyboards",
    platform: "Mobile",
    description: "Show appropriate keyboard for input type",
    doText: "Use inputmode attribute",
    dontText: "Default keyboard for all inputs",
    severity: "Medium",
  },
  {
    id: "64-mobile-first",
    category: "Responsive",
    issue: "Mobile First",
    platform: "Web",
    description: "Design for mobile then enhance for larger",
    doText: "Start with mobile styles then add breakpoints",
    dontText: "Desktop-first causing mobile issues",
    severity: "Medium",
  },
  {
    id: "65-breakpoint-testing",
    category: "Responsive",
    issue: "Breakpoint Testing",
    platform: "Web",
    description: "Test at all common screen sizes",
    doText: "Test at 320 375 414 768 1024 1440",
    dontText: "Only test on your device",
    severity: "Medium",
  },
  {
    id: "66-touch-friendly",
    category: "Responsive",
    issue: "Touch Friendly",
    platform: "Web",
    description: "Mobile layouts need touch-sized targets",
    doText: "Increase touch targets on mobile",
    dontText: "Same tiny buttons on mobile",
    severity: "High",
  },
  {
    id: "67-readable-font-size",
    category: "Responsive",
    issue: "Readable Font Size",
    platform: "All",
    description: "Text must be readable on all devices",
    doText: "Minimum 16px body text on mobile",
    dontText: "Tiny text on mobile",
    severity: "High",
  },
  {
    id: "68-viewport-meta",
    category: "Responsive",
    issue: "Viewport Meta",
    platform: "Web",
    description: "Set viewport for mobile devices",
    doText: "Use width=device-width initial-scale=1",
    dontText: "Missing or incorrect viewport",
    severity: "High",
  },
  {
    id: "69-horizontal-scroll",
    category: "Responsive",
    issue: "Horizontal Scroll",
    platform: "Web",
    description: "Avoid horizontal scrolling",
    doText: "Ensure content fits viewport width",
    dontText: "Content wider than viewport",
    severity: "High",
  },
  {
    id: "70-image-scaling",
    category: "Responsive",
    issue: "Image Scaling",
    platform: "Web",
    description: "Images should scale with container",
    doText: "Use max-width: 100% on images",
    dontText: "Fixed width images overflow",
    severity: "Medium",
  },
  {
    id: "71-table-handling",
    category: "Responsive",
    issue: "Table Handling",
    platform: "Web",
    description: "Tables can overflow on mobile",
    doText: "Use horizontal scroll or card layout",
    dontText: "Wide tables breaking layout",
    severity: "Medium",
  },
  {
    id: "72-line-height",
    category: "Typography",
    issue: "Line Height",
    platform: "All",
    description: "Adequate line height improves readability",
    doText: "Use 1.5-1.75 for body text",
    dontText: "Cramped or excessive line height",
    severity: "Medium",
  },
  {
    id: "73-line-length",
    category: "Typography",
    issue: "Line Length",
    platform: "Web",
    description: "Long lines are hard to read",
    doText: "Limit to 65-75 characters per line",
    dontText: "Full-width text on large screens",
    severity: "Medium",
  },
  {
    id: "74-font-size-scale",
    category: "Typography",
    issue: "Font Size Scale",
    platform: "All",
    description: "Consistent type hierarchy aids scanning",
    doText: "Use consistent modular scale",
    dontText: "Random font sizes",
    severity: "Medium",
  },
  {
    id: "75-font-loading",
    category: "Typography",
    issue: "Font Loading",
    platform: "Web",
    description: "Fonts should load without layout shift",
    doText: "Reserve space with fallback font",
    dontText: "Layout shift when fonts load",
    severity: "Medium",
  },
  {
    id: "76-contrast-readability",
    category: "Typography",
    issue: "Contrast Readability",
    platform: "All",
    description: "Body text needs good contrast",
    doText: "Use darker text on light backgrounds",
    dontText: "Gray text on gray background",
    severity: "High",
  },
  {
    id: "77-heading-clarity",
    category: "Typography",
    issue: "Heading Clarity",
    platform: "All",
    description: "Headings should stand out from body",
    doText: "Clear size/weight difference",
    dontText: "Headings similar to body text",
    severity: "Medium",
  },
  {
    id: "78-loading-indicators",
    category: "Feedback",
    issue: "Loading Indicators",
    platform: "All",
    description: "Show system status during waits",
    doText: "Show spinner/skeleton for operations > 300ms",
    dontText: "No feedback during loading",
    severity: "High",
  },
  {
    id: "79-empty-states",
    category: "Feedback",
    issue: "Empty States",
    platform: "All",
    description: "Guide users when no content exists",
    doText: "Show helpful message and action",
    dontText: "Blank empty screens",
    severity: "Medium",
  },
  {
    id: "80-error-recovery",
    category: "Feedback",
    issue: "Error Recovery",
    platform: "All",
    description: "Help users recover from errors",
    doText: "Provide clear next steps",
    dontText: "Error without recovery path",
    severity: "Medium",
  },
  {
    id: "81-progress-indicators",
    category: "Feedback",
    issue: "Progress Indicators",
    platform: "All",
    description: "Show progress for multi-step processes",
    doText: "Step indicators or progress bar",
    dontText: "No indication of progress",
    severity: "Medium",
  },
  {
    id: "82-toast-notifications",
    category: "Feedback",
    issue: "Toast Notifications",
    platform: "All",
    description: "Transient messages for non-critical info",
    doText: "Auto-dismiss after 3-5 seconds",
    dontText: "Toasts that never disappear",
    severity: "Medium",
  },
  {
    id: "83-confirmation-messages",
    category: "Feedback",
    issue: "Confirmation Messages",
    platform: "All",
    description: "Confirm successful actions",
    doText: "Brief success message",
    dontText: "Silent success",
    severity: "Medium",
  },
  {
    id: "84-truncation",
    category: "Content",
    issue: "Truncation",
    platform: "All",
    description: "Handle long content gracefully",
    doText: "Truncate with ellipsis and expand option",
    dontText: "Overflow or broken layout",
    severity: "Medium",
  },
  {
    id: "85-date-formatting",
    category: "Content",
    issue: "Date Formatting",
    platform: "All",
    description: "Use locale-appropriate date formats",
    doText: "Use relative or locale-aware dates",
    dontText: "Ambiguous date formats",
    severity: "Low",
  },
  {
    id: "86-number-formatting",
    category: "Content",
    issue: "Number Formatting",
    platform: "All",
    description: "Format large numbers for readability",
    doText: "Use thousand separators or abbreviations",
    dontText: "Long unformatted numbers",
    severity: "Low",
  },
  {
    id: "87-placeholder-content",
    category: "Content",
    issue: "Placeholder Content",
    platform: "All",
    description: "Show realistic placeholders during dev",
    doText: "Use realistic sample data",
    dontText: "Lorem ipsum everywhere",
    severity: "Low",
  },
  {
    id: "88-user-freedom",
    category: "Onboarding",
    issue: "User Freedom",
    platform: "All",
    description: "Users should be able to skip tutorials",
    doText: "Provide Skip and Back buttons",
    dontText: "Force linear unskippable tour",
    severity: "Medium",
  },
  {
    id: "89-autocomplete",
    category: "Search",
    issue: "Autocomplete",
    platform: "Web",
    description: "Help users find results faster",
    doText: "Show predictions as user types",
    dontText: "Require full type and enter",
    severity: "Medium",
  },
  {
    id: "90-no-results",
    category: "Search",
    issue: "No Results",
    platform: "Web",
    description: "Dead ends frustrate users",
    doText: "Show 'No results' with suggestions",
    dontText: "Blank screen or '0 results'",
    severity: "Medium",
  },
  {
    id: "91-bulk-actions",
    category: "Data Entry",
    issue: "Bulk Actions",
    platform: "Web",
    description: "Editing one by one is tedious",
    doText: "Allow multi-select and bulk edit",
    dontText: "Single row actions only",
    severity: "Low",
  },
  {
    id: "92-disclaimer",
    category: "AI Interaction",
    issue: "Disclaimer",
    platform: "All",
    description: "Users need to know they talk to AI",
    doText: "Clearly label AI generated content",
    dontText: "Present AI as human",
    severity: "High",
  },
  {
    id: "93-streaming",
    category: "AI Interaction",
    issue: "Streaming",
    platform: "All",
    description: "Waiting for full text is slow",
    doText: "Stream text response token by token",
    dontText: "Show loading spinner for 10s+",
    severity: "Medium",
  },
  {
    id: "94-gaze-hover",
    category: "Spatial UI",
    issue: "Gaze Hover",
    platform: "VisionOS",
    description: "Elements should respond to eye tracking before pinch",
    doText: "Scale/highlight element on look",
    dontText: "Static element until pinch",
    severity: "High",
  },
  {
    id: "95-depth-layering",
    category: "Spatial UI",
    issue: "Depth Layering",
    platform: "VisionOS",
    description: "UI needs Z-depth to separate content from environment",
    doText: "Use glass material and z-offset",
    dontText: "Flat opaque panels blocking view",
    severity: "Medium",
  },
  {
    id: "96-auto-play-video",
    category: "Sustainability",
    issue: "Auto-Play Video",
    platform: "Web",
    description: "Video consumes massive data and energy",
    doText: "Click-to-play or pause when off-screen",
    dontText: "Auto-play high-res video loops",
    severity: "Medium",
  },
  {
    id: "97-asset-weight",
    category: "Sustainability",
    issue: "Asset Weight",
    platform: "Web",
    description: "Heavy 3D/Image assets increase carbon footprint",
    doText: "Compress and lazy load 3D models",
    dontText: "Load 50MB textures",
    severity: "Medium",
  },
  {
    id: "98-feedback-loop",
    category: "AI Interaction",
    issue: "Feedback Loop",
    platform: "All",
    description: "AI needs user feedback to improve",
    doText: "Thumps up/down or 'Regenerate'",
    dontText: "Static output only",
    severity: "Low",
  },
  {
    id: "99-motion-sensitivity",
    category: "Accessibility",
    issue: "Motion Sensitivity",
    platform: "All",
    description: "Parallax/Scroll-jacking causes nausea",
    doText: "Respect prefers-reduced-motion",
    dontText: "Force scroll effects",
    severity: "High",
  },
];

export interface UxPriorityCategory {
  priority: number;
  category: string;
  impact: string;
  domain: string;
  mustHave: string;
  avoid: string;
}

export const UX_PRIORITY_CATEGORIES: UxPriorityCategory[] = [
  {
    priority: 1,
    category: "Accessibility",
    impact: "CRITICAL",
    domain: "ux",
    mustHave: "Contrast 4.5:1, Alt text, Keyboard nav, Aria-labels",
    avoid: "Removing focus rings, Icon-only buttons without labels",
  },
  {
    priority: 2,
    category: "Touch & Interaction",
    impact: "CRITICAL",
    domain: "ux",
    mustHave: "Min size 44×44px, 8px+ spacing, Loading feedback",
    avoid: "Reliance on hover only, Instant state changes (0ms)",
  },
  {
    priority: 3,
    category: "Performance",
    impact: "HIGH",
    domain: "ux",
    mustHave: "WebP/AVIF, Lazy loading, Reserve space (CLS < 0.1)",
    avoid: "Layout thrashing, Cumulative Layout Shift",
  },
  {
    priority: 4,
    category: "Style Selection",
    impact: "HIGH",
    domain: "style, product",
    mustHave: "Match product type, Consistency, SVG icons (no emoji)",
    avoid: "Mixing flat & skeuomorphic randomly, Emoji as icons",
  },
  {
    priority: 5,
    category: "Layout & Responsive",
    impact: "HIGH",
    domain: "ux",
    mustHave: "Mobile-first breakpoints, Viewport meta, No horizontal scroll",
    avoid: "Horizontal scroll, Fixed px container widths, Disable zoom",
  },
  {
    priority: 6,
    category: "Typography & Color",
    impact: "MEDIUM",
    domain: "typography, color",
    mustHave: "Base 16px, Line-height 1.5, Semantic color tokens",
    avoid: "Text < 12px body, Gray-on-gray, Raw hex in components",
  },
  {
    priority: 7,
    category: "Animation",
    impact: "MEDIUM",
    domain: "ux",
    mustHave: "Duration 150–300ms, Motion conveys meaning, Spatial continuity",
    avoid: "Decorative-only animation, Animating width/height, No reduced-motion",
  },
  {
    priority: 8,
    category: "Forms & Feedback",
    impact: "MEDIUM",
    domain: "ux",
    mustHave: "Visible labels, Error near field, Helper text, Progressive disclosure",
    avoid: "Placeholder-only label, Errors only at top, Overwhelm upfront",
  },
  {
    priority: 9,
    category: "Navigation Patterns",
    impact: "HIGH",
    domain: "ux",
    mustHave: "Predictable back, Bottom nav ≤5, Deep linking",
    avoid: "Overloaded nav, Broken back behavior, No deep links",
  },
  {
    priority: 10,
    category: "Charts & Data",
    impact: "LOW",
    domain: "chart",
    mustHave: "Legends, Tooltips, Accessible colors",
    avoid: "Relying on color alone to convey meaning",
  },
];
